import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Provider } from 'react-redux'
// import { makeStore, AppStore } from '../lib/store'

const inter = Inter({ subsets: ['latin'] })

// const store: AppStore = makeStore();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: 
{
  children: React.ReactNode
}) 
{
  return (

    // <Provider store={store}>

      <html lang="en">
        <body className={inter.className}>
          {/* <Provider store={store} > */}

            {children}

          {/* </Provider> */}
          
          </body>
      </html>

    // </Provider>


  )
}
